version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/visionlib
    steps:
      - checkout
      - run: sudo apt-get install python3.6
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo apt-get install build-essential cmake
            sudo apt-get install libopenblas-dev liblapack-dev 
            python -m pip install --upgrade pip
            pip install .
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            cd tests
            python3 -m unittest
          name: Test
