version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/visionlib
    steps:
      - checkout
      - run: sudo apt-get install software-properties-common
      - run: sudo add-apt-repository ppa:deadsnakes/ppa 
      - run: sudo apt-get update
      - run: sudo apt-get install python3.6
      - run:
          command: |
            sudo apt-get install build-essential cmake
            sudo apt-get install libopenblas-dev liblapack-dev 
            python -m pip install --upgrade pip
            pip3 install .
      - run:
          command: |
            cd tests
            python3 -m unittest
          name: Test
